---
- name: install operators
  hosts: localhost
  vars:
    manifests_dir: "/tmp/manifests"
  pre_tasks:
    - name: Create directory for all manifests
      file:
        path: "{{ manifests_dir }}"
        state: directory
        mode: 0644

  tasks:
    - name: Include install_operators role
      include_role:
        name: install_operator
      vars:
        operator_name: "{{ operators_var.name }}"
        operator_namespace: "{{ operators_var.namespace }}"
      loop:
        - {name: openshift-gitops-operator, namespace: openshift-operators}
        - {name: dynatrace-operator, namespace: dynatrace}
        - {name: compliance-operator, namespace: openshift-compliance}
        - {name: serverless-operator, namespace: openshift-serverless}
      loop_control:
        loop_var: operators_var
