image::https://github.com/r3dact3d/OpenShift4-Ansible-Roles/actions/workflows/linter.yaml/badge.svg[link="https://github.com/r3dact3d/OpenShift4-Ansible-Roles/actions/workflows/linter.yaml"]

image::https://github.com/r3dact3d/OpenShift4-Ansible-Roles/actions/workflows/runner.yaml/badge.svg[link="https://github.com/r3dact3d/OpenShift4-Ansible-Roles/actions/workflows/runner.yaml"]

== Purpose

To provide reusable automation to run ansible plays and roles against OpenShift 4 clusters

NOTE: This will always pull the latest *stable* OpenShift 4 CLI tools

== Requirements

You will need an OpenShift 4 cluster deployed with access to the kubeconfig

== Roles

* Add any addition modules to requirements.txt with `openshift` listed

=== Deploy-Operator

. Create repository secret in GitHub Settings > Secrets called KUBECONFIG that contains kubeconfig details
. Update ansible playbook called main.yaml to ensure *vars* are set
.. `ansible_python_interpreter: /usr/bin/python3`
.. `OPERATOR-NAME: web-terminal`  [red yellow-background]#put operator to install here#
.. `NAMESPACE: openshift-operators`  [red yellow-background]#put namespace to install operator at here#

== Workflow

Once the main branch is pushed with updates to main.yaml the workflow will trigger the actions that will run *ansible-playbook*.

This is intended to simulate running Ansible playbooks to engineer, operate, or manage OpenShift 4 clusters on a bastion host.  The playbook is intended to run locally on runner and use  either `oc`, `kubectl`, or other modules that interact with OpenShift APIs or any APIs.
